name: build linux kernel with openzfs

on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        echo "Free space:"
        df -h
        
    container: archlinux:base-devel
    
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git base-devel python cpio pahole bc libelf perl xz

    - name: Show PKGBUILD content
      run: |
        pwd
        ls -la
        cat PKGBUILD

    - name: Build package
      run: |
        useradd builder -m
        chown -R builder:builder .
        cd "$GITHUB_WORKSPACE"
        su builder -c 'makepkg -sf --noconfirm --skippgpcheck --skipchecksums'

    - name: List built packages
      run: |
        ls -la *.pkg.tar.zst

    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: ./*.pkg.tar.zst
        retention-days: 90
